### ISSUE TITLE
Create a simple To-Do website with the given specifications

### ISSUE THREAD

**Issue by Diptonil** [Pranavv213/WebDevForBeginners#15]
## A simple To-Do list website can be made using HTML, CSS and JavaScript. It should have the following specifications:
1. **Separate folders of CSS, HTML and JavaScript**: Separate all the files into the respective directories for proper adherence to structure.
2. **Use simple CSS or Bootstrap**: To style the website, either of the two options may be used. Aesthetics are completely up to you.
3. **Use vanilla JavaScript**: No frameworks need to be used for high-level functionality.
4. **Ensure the code looks clean and is readable**: Dangling indentations, useless blank lines should be refrained from.
5. **Document steps** (optional): Document all steps in a markdown file that you took to create the website.

**Comment by Soumyajit2825** [comment]
@Diptonil Can I work on it?

**Comment by sumit-022** [comment]
I can work on this. Please assign me

**Comment by Diptonil** [comment]
The PR will be merged soon. It is pending another review.
