### ISSUE TITLE
Design a simple website using plain Bootstrap

### ISSUE THREAD

**Issue by Diptonil** [Pranavv213/WebDevForBeginners#16]
## A simple website of your choice is to be designed such that following measures are maintained:
1. **All components of a web UI are to be included**: The website should be aesthetically wholesome with navbars, menus, styles buttons, footers, etc.
2. **Bootstrap**: Simple concepts of Bootstrap should be compulsorily used.
3. **Documentation**: Create a markdown file documenting all steps taken to accomplish the goal. Technical details need to be mentioned in passing without extreme elaborations.
4. **Conventions**: Code conventions and standards are compulsory to be taken care of. No stray indentations, line breaks, poor structure would be considered.

**Comment by harsitagarwalla187** [comment]
Can you aasign me this issue?

**Comment by harsitagarwalla187** [comment]
![2](https://user-images.githubusercontent.com/84774840/194082911-5062c4a6-26ce-42ac-aa4f-48217d39a107.png)
![3](https://user-images.githubusercontent.com/84774840/194082935-9326d6de-9be2-4857-8eba-9ed827b22b9b.png)
![1](https://user-images.githubusercontent.com/84774840/194082943-3b664d64-6025-4f2e-8fca-3184a507690d.png)

**Comment by Diptonil** [comment]
If you have done the work, @harsitagarwalla187, please make a PR and work your way towards a merge.

**Comment by harsitagarwalla187** [comment]
OK
