### ISSUE TITLE
Create a folder of ur name and create an HTML inside it  with a background color blue having some basic information about yourself with <your_name>.html extension

### ISSUE THREAD

**Issue by Pranavv213** [Pranavv213/WebDevForBeginners#9]
![WhatsApp Image 2022-10-04 at 7 57 31 PM](https://user-images.githubusercontent.com/98053577/193846412-83ecf35a-d824-418a-9dbb-5e512e85468c.jpeg)

**Comment by Pranavv213** [comment]
> @Pranavv213 I can do this , please assign this to me.

ok , go ahead

**Comment by Ankita-278** [comment]
@Pranavv213 I also want to contribute to this issue.Can you pls assign this to me?

**Comment by unicorn2022wbdev** [comment]
@Pranavv213 Can you even assign me this issue!

**Comment by Harshvardhan-Dubey-Github** [comment]
I want to work on this
